name: Flutter CI/CD APK to Telegram

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🛠 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: false

      - name: 🔍 Check Flutter Version
        run: flutter --version

      - name: 📦 Get Dependencies
        run: flutter pub get

      - name: 🏗 Build APK Release
        run: flutter build apk --release

      - name: 📁 Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk app-release.apk

      - name: 📤 Send APK to Telegram
        run: |
          curl -F document=@app-release.apk \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument \
          -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -F caption="🚀 APK terbaru berhasil di build!"